### PR TITLE
Scripted Modifiers and other misc. additions.

### PR DESCRIPTION
**Pull request by Zonr0**
NOTE: Check for potential conflicts and redundancies with PR #19! Basic preview shows they're able to merge, but there are probably redundancies at least.

Various small tweaks and additions created while working on effects and triggers. Wanted to PR this before they got stale.

Fixes:

Changes:
* Changes some description keys to use new complex desc alias

Additions:
* New complex desc type attempting to consolidate different desc alias that had been defined
* New weight:modifier alias for random and weight modifiers. lso should pick up scripted modifiers.
* Initial scripted modifier support
* LHS Duration alias
* Event option skills enum.
* Basic placeholder implementation for animations.

### CODE REVIEW

**Comment by Zonr0** [comment]
Related to #19  . Probably would be a good idea for someone to checkout both of these PRs, merge them, and PR the resulting merge.

Will do this later tonight or tomorrow if I have time, but may not get to it so if someone wants to beat me to it, go right ahead.

**Comment by Ernie0013** [comment]
@Zonr0 Done, your changes are now also in #19 
I made sure we didn't have two `scripted_modifiers.cwt`. Merged a few lines of mine into yours, but I did move it into the common folder where mine was.

**Comment by Ernie0013** [comment]
Done. I created a new PR #23 because I screwed up the other one by committing stuff under a different user.

**Comment by Zonr0** [comment]
Superceded by #23

**Pull request closed without merging**
